SELECT fact.*, sf.co_op_oem__c, sf.co_op_product_suite__c
FROM (
SELECT
    COUNT(DISTINCT VEHICLE_DAILY_VW.VEHICLE_ID) VEHICLES,
    STOCK_TYPE_VW.NEW_USED_IND,
    MAKE_VW.MAKE_NAME,
    VEHICLE_MAKE_MODEL_VW.MODEL_NAME,
    MODEL_YEAR_VW.MODEL_YEAR,
    VEHICLE_VW.VIN,
    VEHICLE_VW.DEALER_STOCK_NUM,
    CUSTOMER_VW.CUSTOMER_NAME,
    DATE_DIM_VW.MONTH_NAME,
    DATE_DIM_VW.FIRST_DATE_OF_MONTH,
    VEHICLE_VW.CPO_IND,
    CUSTOMER_VW.LEGACY_ID
FROM dw_vw.CUSTOMER_VW
INNER JOIN dw_vw.VEHICLE_DAILY_VW  ON (CUSTOMER_VW.CUSTOMER_ID=VEHICLE_DAILY_VW.CUSTOMER_ID)
INNER JOIN dw_vw.VEHICLE_MAKE_MODEL_VW ON (VEHICLE_MAKE_MODEL_VW.MAKE_MODEL_ID=VEHICLE_DAILY_VW.MAKE_MODEL_ID)
INNER JOIN dw_vw.MAKE_VW ON (MAKE_VW.MAKE_ID=VEHICLE_DAILY_VW.MAKE_ID)
INNER JOIN dw_vw.DATE_DIM_VW ON (DATE_DIM_VW.DATE_ID=VEHICLE_DAILY_VW.DATE_ID)
INNER JOIN dw_vw.MODEL_YEAR_VW ON (MODEL_YEAR_VW.MODEL_YEAR_ID=VEHICLE_DAILY_VW.MODEL_YEAR_ID)
INNER JOIN dw_vw.STOCK_TYPE_VW ON (STOCK_TYPE_VW.STOCK_TYPE_ID=VEHICLE_DAILY_VW.STOCK_TYPE_ID)
INNER JOIN dw_vw.VEHICLE_VW ON (VEHICLE_DAILY_VW.VEHICLE_ID=VEHICLE_VW.VEHICLE_ID)
WHERE (DATE_DIM_VW.first_date_of_month >= last_day(add_months(current_date,-7)) + 1  and DATE_DIM_VW.first_date_of_month <= last_day(add_months(current_date,-2)) + 1)
GROUP BY 2,3,4,5,6,7,8,9,10,11,12) fact
LEFT JOIN (
    SELECT ccid__c, co_op_oem__c, co_op_product_suite__c
    FROM raw_ext.salesforce_onecars_account_raw
    WHERE DATE(aday) BETWEEN DATEADD('month', -1, DATE_TRUNC('month', current_date))
    AND DATE_TRUNC('month', current_date)-1
    QUALIFY ROW_NUMBER() OVER(PARTITION BY ccid__c ORDER BY aday DESC) = 1) sf ON fact.legacy_id = sf.ccid__c